freebsd_instance:
  image: freebsd-12-2-release-amd64
env:
  RUST_BACKTRACE: full
task:
  name: FreeBSD
  timeout_in: 15m
  cargo_cache:
    folder: $HOME/.cargo/registry
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --profile minimal --default-toolchain nightly
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
