edition = "Edition2018"
unstable_features = true

binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Compressed"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Horizontal"
indent_style = "Block"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 120
merge_derives = true
merge_imports = false # This merges from `crate::` which is ugly.
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 0 # TODO: set this to a nice value.
struct_lit_single_line = false
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true # TODO: check
wrap_comments = true
