os:
  - linux
  - osx
language: rust
env:
  - RUST_BACKTRACE=full
rust:
  - nightly
matrix:
  fast_finish: false
  include:
    - rust: nightly
      name: "Clippy check"
      # Failing the `cognitive-complexity' lint is allowed because the tests are
      # too complex.
      script:
        - rustup component add clippy
        - cargo clippy --all-targets --all-features -- -D warnings -A clippy::cognitive-complexity
script:
  - cargo --version
  - rustc --version
  - cargo test --verbose --all-features
