os:
  - linux
  - osx
language: rust
env:
  - RUST_BACKTRACE=full
rust:
  - nightly
matrix:
  fast_finish: false
  include:
    - rust: nightly
      name: "Clippy check"
      script: ./.ci/clippy.sh
    - rust: stable
      name: "Format check"
      script: ./.ci/fmt.sh
script: ./.ci/test.sh
