cache: cargo
os:
  - linux
  - osx
language: rust
env:
  - RUST_BACKTRACE=1
rust:
  - nightly
matrix:
  fast_finish: true
script:
  - cargo --version
  - rustc --version
  - cargo test --verbose --all-features
