[package]
name = "actor"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
fnv = "1.0.6"
futures = { version = "0.1.17", default-features = false, features = ["use_std"] }
log = "0.4.0-rc.1"
mio = "0.6.11"
tchannel = { git = "https://github.com/Thomasdezeeuw/tchannel" }
