[package]
name          = "heph"
description   = "Heph is an actor framework based on asynchronous functions."
version       = "0.2.0-dev"
authors       = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license       = "MIT"
documentation = "https://docs.rs/heph"
repository    = "https://github.com/Thomasdezeeuw/heph"
readme        = "README.md"
keywords      = ["actor", "framework", "async", "functions"]
categories    = ["asynchronous", "web-programming"]
include       = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/heph", branch = "master" }

[features]
default = []

# Feature that enables the `test` module.
test = []

[dependencies]
crossbeam-channel    = "0.3.6"
futures-core-preview = "0.3.0-alpha.17"
futures-io-preview   = "0.3.0-alpha.17"
log                  = "0.4.6"
gaea                 = "0.3.0"
num_cpus             = "1.8.0"
slab                 = "0.4.0"
std-logger           = "0.3.4"

[dev-dependencies]
futures-test-preview = "0.3.0-alpha.17"
futures-util-preview = { version = "0.3.0-alpha.17", features = ["nightly", "async-await", "select-macro"] }
lazy_static          = "1.1.0"
