cargo-features = ["edition"]

[package]
name = "heph"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/heph" }

[features]
default = []

# The feature that enables the `test` module.
test = []

[dependencies]
crossbeam-channel    = "0.2.4"
futures-core-preview = "0.3.0-alpha.3"
futures-io-preview   = "0.3.0-alpha.3"
log                  = "0.4.2"
num_cpus             = "1.8.0"
slab                 = "0.4.0"

# Replace with published crate.
mio-st = { git = "ssh://git@github.com/Thomasdezeeuw/mio-st.git" }

[dev-dependencies]
env_logger           = "0.5.10"
futures-util-preview = "0.3.0-alpha.3"
lazy_static          = "1.1.0"
