[package]
name          = "heph"
description   = "Heph is an actor framework based on asynchronous functions."
version       = "0.3.1"
authors       = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license       = "MIT"
documentation = "https://docs.rs/heph"
repository    = "https://github.com/Thomasdezeeuw/heph"
readme        = "README.md"
keywords      = ["actor", "framework", "async", "functions"]
categories    = ["asynchronous", "web-programming"]
include       = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE"]
edition       = "2018"

[features]
default = []

# Feature that enables the `test` module.
test = ["getrandom"]

[dependencies]
crossbeam-channel = { version = "0.5.0", default-features = false, features = ["std"] }
heph-inbox        = { version = "0.2.1", default-features = false }
libc              = { version = "0.2.96", default-features = false }
log               = { version = "0.4.16", default-features = false, features = ["kv_unstable"] }
mio               = { version = "0.8.0", default-features = false, features = ["os-poll", "net"] }
mio-signals       = { version = "0.2.0", default-features = false }
socket2           = { version = "0.4.0", default-features = false, features = ["all"] }

# Optional dependencies, enabled by features.
# Required by the `test` feature.
getrandom         = { version = "0.2.2", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
getrandom         = { version = "0.2.2", default-features = false, features = ["std"] }
# Enable logging panics via `std-logger`.
std-logger        = { version = "0.4.0", default-features = false, features = ["log-panic", "nightly"] }

[[test]]
name    = "process_signals"
# Require full control over the spawned threads.
harness = false

[workspace]
members = [
  #"http", # Stuck on 2021-11-01.
  "remote",
  "tools",

  "benches/timers_container",
]
