cargo-features = ["edition"]

[package]
name = "actor"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT"

edition = "2018"

[features]
default = []

# Add facilities to be used when testing.
test = []

[dependencies]
futures-core-preview = "0.3.0-alpha.2"
futures-io-preview   = "0.3.0-alpha.2"
log                  = "0.4.2"
num_cpus             = "1.8.0"
slab                 = "0.4.0"

# Replace with published crate.
mio-st = { git = "ssh://git@github.com/Thomasdezeeuw/mio-st.git" }

[dev-dependencies]
env_logger = "0.5.10"
futures-util-preview = "0.3.0-alpha.1"
