[package]
name        = "heph"
version     = "0.2.0-dev"
authors     = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license     = "MIT"
description = """
Heph is an actor framework based on asynchronous functions.
"""
readme        = "README.md"
repository    = "https://github.com/Thomasdezeeuw/heph"
documentation = "https://docs.rs/heph"
keywords      = ["actor", "framework", "async", "functions"]
categories    = ["asynchronous", "web-programming"]
include       = ["Cargo.toml", "src/**/*.rs", "LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "https://github.com/Thomasdezeeuw/heph", branch = "master" }

[features]
default = []

# The feature that enables the `test` module.
test = []

[dependencies]
crossbeam-channel    = "0.2.4"
futures-core-preview = "0.3.0-alpha.9"
futures-io-preview   = "0.3.0-alpha.9"
log                  = "0.4.6"
mio-st               = "0.1.0"
num_cpus             = "1.8.0"
slab                 = "0.4.0"
std-logger           = "0.3.1"

[dev-dependencies]
env_logger           = "0.5.10"
futures-util-preview = "0.3.0-alpha.9"
lazy_static          = "1.1.0"
