[package]
name = "actor"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
futures = { version = "0.1.17", default-features = false }
