cargo-features = ["edition"]

[package]
name = "actor"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT"

edition = "2018"

[features]
default = []

# Add facilities to be used when testing.
test = []

[dependencies]
log = "0.4.2"
num_cpus = "1.8.0"
slab = "0.4.0"

# Replace with published crate.
mio-st = { path = '../mio-st' }

[dev-dependencies]
env_logger = "0.5.10"
