[package]
name          = "heph"
description   = "Heph is an actor framework based on asynchronous functions."
version       = "0.2.0-dev"
authors       = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license       = "MIT"
documentation = "https://docs.rs/heph"
repository    = "https://github.com/Thomasdezeeuw/heph"
readme        = "README.md"
keywords      = ["actor", "framework", "async", "functions"]
categories    = ["asynchronous", "web-programming"]
include       = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/heph", branch = "master" }

[features]
default = []

# Feature that enables the `test` module.
test = []

[dependencies]
crossbeam-channel = { version = "0.4.0", default-features = false }
erased-serde      = { version = "0.3.11", default-features = false, features = ["std"] }
fnv               = { version = "1.0.6", default-features = false }
futures-core      = { version = "0.3.4", default-features = false }
futures-io        = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util      = { version = "0.3.4", default-features = false }
lazy_static       = { version = "1.4.0", default-features = false }
log               = { version = "0.4.8", default-features = false }
mio               = { version = "0.7.0", default-features = false, features = ["os-poll", "tcp", "udp"] }
mio-pipe          = { version = "0.1.0", default-features = false }
mio-signals       = { version = "0.1.1", default-features = false }
num_cpus          = { version = "1.12.0", default-features = false }
parking_lot       = { version = "0.10.0", default-features = false, features = ["nightly"] }
rand              = { version = "0.7.3", default-features = false, features = ["std"] }
serde             = { version = "1.0.105", default-features = false, features = ["derive"] }
serde_json        = { version = "1.0.52", default-features = false, features = ["std"] }
# Enable logging panics via `std-logger` and add timestamps to each log message.
std-logger        = { version = "0.3.6", default-features = false, features = ["log-panic", "timestamp"] }

[dev-dependencies]
futures-test = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util = { version = "0.3.4", default-features = false, features = ["async-await-macro"] }
