[package]
name          = "heph"
description   = "Heph is an actor framework based on asynchronous functions."
version       = "0.2.0-dev"
authors       = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license       = "MIT"
documentation = "https://docs.rs/heph"
repository    = "https://github.com/Thomasdezeeuw/heph"
readme        = "README.md"
keywords      = ["actor", "framework", "async", "functions"]
categories    = ["asynchronous", "web-programming"]
include       = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/heph", branch = "master" }

[features]
default = []

# Feature that enables the `test` module.
test = ["rand"]

[dependencies]
crossbeam-channel = { version = "0.5.0", default-features = false, features = ["std"] }
futures-core      = { version = "0.3.6", default-features = false }
futures-io        = { version = "0.3.6", default-features = false, features = ["std"] }
# FIXME: use released version.
inbox             = { git = "https://github.com/Thomasdezeeuw/inbox", rev = "35f4269f07a5dd717c08e20cc5e260bd980462f0" }
libc              = { version = "0.2.79", default-features = false }
log               = { version = "0.4.8", default-features = false }
mio               = { version = "0.7.5", default-features = false, features = ["os-poll", "tcp", "udp", "pipe"] }
mio-signals       = { version = "0.1.2", default-features = false }
# Enable logging panics via `std-logger` and add timestamps to each log message.
std-logger        = { version = "0.3.6", default-features = false, features = ["log-panic", "timestamp"] }

# Required by the `test` feature.
rand              = { version = "0.7.3", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
futures-test      = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util      = { version = "0.3.4", default-features = false, features = ["async-await-macro"] }
rand              = { version = "0.7.3", default-features = false, features = ["std"] }
