[package]
name = "heph"
description = """
Heph is an actor framework based on asynchronous functions.
"""
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license = "MIT"
repository = "https://github.com/Thomasdezeeuw/heph"
readme = "README.md"
keywords = ["actor", "framework", "async", "functions"]
edition = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/heph" }

[features]
default = []

# The feature that enables the `test` module.
test = []

[dependencies]
crossbeam-channel    = "0.2.4"
futures-core-preview = "0.3.0-alpha.6"
futures-io-preview   = "0.3.0-alpha.6"
log                  = "0.4.2"
mio-st               = "0.1.0"
num_cpus             = "1.8.0"
slab                 = "0.4.0"
std-logger           = "0.3.1"

[dev-dependencies]
env_logger           = "0.5.10"
futures-util-preview = "0.3.0-alpha.6"
lazy_static          = "1.1.0"
