name: 'Test with miri'
description: 'Run tests using `make test_miri`.'
inputs:
  test-flags:
    description: 'Additional flags to pass using TEST_FLAGS (see Makefile).'
    required: false
  working-directory:
    description: 'Working directory.'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: dtolnay/rust-toolchain@nightly
    with:
      components: miri
  - name: Run tests
    shell: bash
    run: |
      cd "${{ inputs.working-directory }}"
      TEST_FLAGS="${{ inputs.test-flags }}" make test_miri
