[package]
name = "heph-http"
version = "0.1.0"
edition = "2018"

[dependencies]
heph     = { version = "0.3.0", path = "../", default-features = false }
httparse = { version = "1.4.0", default-features = false }
log      = { version = "0.4.8", default-features = false }
socket2  = { version = "0.4.0", default-features = false, features = ["all"] }

[dev-dependencies]
getrandom         = { version = "0.2.2", default-features = false, features = ["std"] }
# Enable logging panics via `std-logger`.
std-logger        = { version = "0.4.0", default-features = false, features = ["log-panic", "nightly"] }
