[package]
name = "heph-http"
version = "0.1.0"
edition = "2018"

[dependencies]
heph     = { version = "0.3.0", path = "../", default-features = false }
httparse = { version = "1.4.0", default-features = false }
httpdate = { version = "1.0.0", default-features = false }
log      = { version = "0.4.8", default-features = false }

[dev-dependencies]
# Enable logging panics via `std-logger`.
std-logger        = { version = "0.4.0", default-features = false, features = ["log-panic", "nightly"] }
