name: 'Test with sanitizer'
description: 'Run tests using `make test_sanitizer`.'
inputs:
  sanitizer:
    description: 'Sanitizer to use.'
    required: true
  test-flags:
    description: 'Additional flags to pass using TEST_FLAGS (see Makefile).'
    required: false
runs:
  using: 'composite'
  steps:
  - uses: dtolnay/rust-toolchain@nightly
    with:
      components: rust-src
  - name: Run tests with sanitiser
    run: TEST_FLAGS="${{ inputs.test-flags }}" make test_sanitizer sanitizer="${{ inputs.sanitizer }}"
    shell: bash
