name: 'Test with sanitizer'
description: 'Run tests using `make test`.'
inputs:
  sanitizer:
    description: 'Sanitizer to use'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
  - uses: dtolnay/rust-toolchain@nightly
    with:
      components: rust-src
  - name: Run tests with sanitiser
    run: make test_sanitizer sanitizer="${INPUT_SANITIZER}"
