name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --workspace --all-features
