name: Heph-HTTP
on:
  push:
    branches: [ main ]
    paths:
      - "http/**"
      - ".github/workflows/http.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "http/**"
      - ".github/workflows/http.yml"
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # TODO: enable <https://github.com/Thomasdezeeuw/heph/issues/647>.
    if: false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test
      with:
        working-directory: http
  Sanitiser:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # TODO: enable <https://github.com/Thomasdezeeuw/heph/issues/647>.
    if: false
    strategy:
      fail-fast: false
      matrix:
        # LeakSanitizer is broken, see
        # <https://github.com/rust-lang/rust/issues/111073>.
        sanitiser: [address, memory, thread] # leak
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test_sanitizer
      with:
        sanitizer: ${{ matrix.sanitiser }}
        working-directory: http
