name: Heph-inbox
on:
  push:
    branches: [ main ]
    paths:
      - "inbox/**"
      - ".github/workflows/inbox.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "inbox/**"
      - ".github/workflows/inbox.yml"
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # This often run too many iterations on CI, which is not a real error.
    continue-on-error: ${{ matrix.release == 'release' }}
    strategy:
      fail-fast: false
      matrix:
        release: ['', '--release'] # '' => debug.
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test
      with:
        test-flags: ${{ matrix.release }}
        working-directory: inbox
  Miri:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test_miri
      with:
        working-directory: inbox
  Sanitiser:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # LeakSanitizer is broken, see
        # <https://github.com/rust-lang/rust/issues/111073>.
        sanitiser: [address, memory, thread] # leak
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test_sanitizer
      with:
        sanitizer: ${{ matrix.sanitiser }}
        working-directory: inbox
