name: Inbox
on:
  push:
    branches: [ main ]
    paths:
      - "inbox/**"
      - ".github/workflows/inbox.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "inbox/**"
      - ".github/workflows/inbox.yml"
permissions:
  contents: read
defaults:
  run:
    working-directory: inbox
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # This often run too many iterations on CI, which is not a real error.
    continue-on-error: ${{ matrix.release == 'release' }}
    strategy:
      fail-fast: false
      matrix:
        release: ['', release] # '' => debug.
        toolchain: [stable, nightly]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@${{ matrix.toolchain }}
    - name: Run tests
      run: cargo test --verbose --${{ matrix.release }}
    - name: Run stress tests
      run: cargo test --verbose --features stress_testing --${{ matrix.release }}
  Clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: Run Clippy
      run: cargo clippy
  Rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check
  Miri:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    - name: Run tests in Miri
      run: cargo miri test
  Sanitiser:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        sanitiser: [address, leak, memory, thread]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: Run tests with sanitiser
      # NOTE: Keep `RUSTFLAGS` and `RUSTDOCFLAGS` in sync to ensure the doc
      # tests compile correctly.
      run: >
        RUSTFLAGS="-Z sanitizer=${{ matrix.sanitiser }} -Z sanitizer-memory-track-origins"
        RUSTDOCFLAGS="-Z sanitizer=${{ matrix.sanitiser }} -Z sanitizer-memory-track-origins"
        cargo test -Z build-std --target x86_64-unknown-linux-gnu --features unstable_nightly
  Docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all --all-features
