name: Heph-remote
on:
  push:
    branches: [ main ]
    paths:
      - "remote/**"
      - ".github/workflows/remote.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "remote/**"
      - ".github/workflows/remote.yml"
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install Cargo-hack
      run: cargo install --debug cargo-hack
    - uses: ./.github/workflows/test
      with:
        working-directory: remote
  Sanitiser:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        sanitiser: [address, leak, memory, thread]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test_sanitizer
      with:
        sanitizer: ${{ matrix.sanitiser }}
        working-directory: remote
