name: Heph-rt
on:
  push:
    branches: [ main ]
    paths:
      - "rt/**"
      - ".github/workflows/rt.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "rt/**"
      - ".github/workflows/rt.yml"
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test
      with:
        working-directory: rt
  Sanitiser:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # TODO: enable <https://github.com/Thomasdezeeuw/heph/issues/646>.
    if: false
    strategy:
      fail-fast: false
      matrix:
        sanitiser: [address, leak, memory, thread]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test_sanitizer
      with:
        sanitizer: ${{ matrix.sanitiser }}
        working-directory: rt
