name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  test_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly compiler
      run: .github/install.bash
    - name: Run tests
      run: cargo test --verbose
    - name: Run stress tests
      run: cargo test --verbose --features stress_testing
  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly compiler
      run: .github/install.bash
    - name: Add Miri
      run: rustup component add miri
    - name: Run tests in Miri
      # Enable again once Miri supports `libc::nanosleep` without disable-isolation.
      #run: cargo miri test
      run: cargo miri test -- -Zmiri-disable-isolation
